# CMake generated Testfile for 
# Source directory: C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests
# Build directory: C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(OCDAlgorithmTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/Debug/OCDAlgorithmTests.exe")
  set_tests_properties(OCDAlgorithmTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;66;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(OCDAlgorithmTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/Release/OCDAlgorithmTests.exe")
  set_tests_properties(OCDAlgorithmTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;66;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(OCDAlgorithmTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/MinSizeRel/OCDAlgorithmTests.exe")
  set_tests_properties(OCDAlgorithmTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;66;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(OCDAlgorithmTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/RelWithDebInfo/OCDAlgorithmTests.exe")
  set_tests_properties(OCDAlgorithmTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;66;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
else()
  add_test(OCDAlgorithmTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(OCDPluginTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/Debug/OCDPluginTests.exe")
  set_tests_properties(OCDPluginTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;67;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(OCDPluginTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/Release/OCDPluginTests.exe")
  set_tests_properties(OCDPluginTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;67;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(OCDPluginTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/MinSizeRel/OCDPluginTests.exe")
  set_tests_properties(OCDPluginTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;67;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(OCDPluginTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/RelWithDebInfo/OCDPluginTests.exe")
  set_tests_properties(OCDPluginTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;67;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
else()
  add_test(OCDPluginTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(OCDIntegrationTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/Debug/OCDIntegrationTests.exe")
  set_tests_properties(OCDIntegrationTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;68;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(OCDIntegrationTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/Release/OCDIntegrationTests.exe")
  set_tests_properties(OCDIntegrationTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;68;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(OCDIntegrationTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/MinSizeRel/OCDIntegrationTests.exe")
  set_tests_properties(OCDIntegrationTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;68;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(OCDIntegrationTests "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/tests/RelWithDebInfo/OCDIntegrationTests.exe")
  set_tests_properties(OCDIntegrationTests PROPERTIES  ENVIRONMENT "MAYA_PLUG_IN_PATH=C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/build.optimized/plug-ins" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;68;add_test;C:/Users/edurm/divkitBase/plug-ins/plug-ins/offsetCurveDeformer/offsetCurveDeformer/tests/CMakeLists.txt;0;")
else()
  add_test(OCDIntegrationTests NOT_AVAILABLE)
endif()
subdirs("../_deps/googletest-build")
